package Teasy.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_plataforms extends EnumerationDescriptorBase {

  public EnumerationDescriptor_plataforms() {
    super(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x67d09fa70b0d6ce4L, "plataforms", "r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/7480654520856177892");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_Android_0 = new EnumerationDescriptor.MemberDescriptor("Android", "Android", 0x67d09fa70b0d6ce5L, "r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/7480654520856177893");
  private final EnumerationDescriptor.MemberDescriptor myMember_iOS_0 = new EnumerationDescriptor.MemberDescriptor("iOS", "iOS", 0x67d09fa70b0d6d6fL, "r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/7480654520856178031");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x67d09fa70b0d6ce4L, 0x67d09fa70b0d6ce5L, 0x67d09fa70b0d6d6fL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_Android_0, myMember_iOS_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_Android_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "Android":
        return myMember_Android_0;
      case "iOS":
        return myMember_iOS_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
