package Teasy.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_automationNames extends EnumerationDescriptorBase {

  public EnumerationDescriptor_automationNames() {
    super(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x67d09fa70b0d6d5bL, "automationNames", "r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/7480654520856178011");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_XCUITest_0 = new EnumerationDescriptor.MemberDescriptor("XCUITest", "XCUITest (iOS)", 0x67d09fa70b0d6d5cL, "r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/7480654520856178012");
  private final EnumerationDescriptor.MemberDescriptor myMember_Instruments_0 = new EnumerationDescriptor.MemberDescriptor("Instruments", "Instruments (iOS)", 0x67d09fa70b0d6d5dL, "r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/7480654520856178013");
  private final EnumerationDescriptor.MemberDescriptor myMember_UiAutomator2_0 = new EnumerationDescriptor.MemberDescriptor("UiAutomator2", "UiAutomator2 (Android)", 0x67d09fa70b0d6d60L, "r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/7480654520856178016");
  private final EnumerationDescriptor.MemberDescriptor myMember_Espresso_0 = new EnumerationDescriptor.MemberDescriptor("Espresso", "Espresso (Android)", 0x67d09fa70b0d6d64L, "r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/7480654520856178020");
  private final EnumerationDescriptor.MemberDescriptor myMember_UiAutomator1_0 = new EnumerationDescriptor.MemberDescriptor("UiAutomator1", "UiAutomator1 (Android)", 0x67d09fa70b0d6d69L, "r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/7480654520856178025");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x67d09fa70b0d6d5bL, 0x67d09fa70b0d6d5cL, 0x67d09fa70b0d6d5dL, 0x67d09fa70b0d6d60L, 0x67d09fa70b0d6d64L, 0x67d09fa70b0d6d69L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_XCUITest_0, myMember_Instruments_0, myMember_UiAutomator2_0, myMember_Espresso_0, myMember_UiAutomator1_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_UiAutomator2_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "XCUITest":
        return myMember_XCUITest_0;
      case "Instruments":
        return myMember_Instruments_0;
      case "UiAutomator2":
        return myMember_UiAutomator2_0;
      case "Espresso":
        return myMember_Espresso_0;
      case "UiAutomator1":
        return myMember_UiAutomator1_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
