package Teasy.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_StringBoolean extends EnumerationDescriptorBase {

  public EnumerationDescriptor_StringBoolean() {
    super(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x67d09fa70b364e0aL, "StringBoolean", "r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/7480654520858856970");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_True_0 = new EnumerationDescriptor.MemberDescriptor("True", "True", 0x67d09fa70b364e0cL, "r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/7480654520858856972");
  private final EnumerationDescriptor.MemberDescriptor myMember_False_0 = new EnumerationDescriptor.MemberDescriptor("False", "False", 0x67d09fa70b364e0eL, "r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/7480654520858856974");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x67d09fa70b364e0aL, 0x67d09fa70b364e0cL, 0x67d09fa70b364e0eL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_True_0, myMember_False_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_True_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "True":
        return myMember_True_0;
      case "False":
        return myMember_False_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
