package Teasy.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptCapturePageScreenshot = createDescriptorForCapturePageScreenshot();
  /*package*/ final ConceptDescriptor myConceptClearText = createDescriptorForClearText();
  /*package*/ final ConceptDescriptor myConceptClickAPoint = createDescriptorForClickAPoint();
  /*package*/ final ConceptDescriptor myConceptClickElement = createDescriptorForClickElement();
  /*package*/ final ConceptDescriptor myConceptClickElementAtCoordinates = createDescriptorForClickElementAtCoordinates();
  /*package*/ final ConceptDescriptor myConceptClickText = createDescriptorForClickText();
  /*package*/ final ConceptDescriptor myConceptComponent = createDescriptorForComponent();
  /*package*/ final ConceptDescriptor myConceptComponents = createDescriptorForComponents();
  /*package*/ final ConceptDescriptor myConceptConfiguration = createDescriptorForConfiguration();
  /*package*/ final ConceptDescriptor myConceptElementShouldBeDisabled = createDescriptorForElementShouldBeDisabled();
  /*package*/ final ConceptDescriptor myConceptElementShouldBeEnabled = createDescriptorForElementShouldBeEnabled();
  /*package*/ final ConceptDescriptor myConceptElementShouldBeVisible = createDescriptorForElementShouldBeVisible();
  /*package*/ final ConceptDescriptor myConceptElementShouldContainText = createDescriptorForElementShouldContainText();
  /*package*/ final ConceptDescriptor myConceptElementShouldNotContainText = createDescriptorForElementShouldNotContainText();
  /*package*/ final ConceptDescriptor myConceptElementTextShouldBe = createDescriptorForElementTextShouldBe();
  /*package*/ final ConceptDescriptor myConceptExecuteAdbShell = createDescriptorForExecuteAdbShell();
  /*package*/ final ConceptDescriptor myConceptExecuteScript = createDescriptorForExecuteScript();
  /*package*/ final ConceptDescriptor myConceptFlow = createDescriptorForFlow();
  /*package*/ final ConceptDescriptor myConceptFlowItem = createDescriptorForFlowItem();
  /*package*/ final ConceptDescriptor myConceptFlows = createDescriptorForFlows();
  /*package*/ final ConceptDescriptor myConceptHideKeyboard = createDescriptorForHideKeyboard();
  /*package*/ final ConceptDescriptor myConceptHooks = createDescriptorForHooks();
  /*package*/ final ConceptDescriptor myConceptInputPassword = createDescriptorForInputPassword();
  /*package*/ final ConceptDescriptor myConceptInputText = createDescriptorForInputText();
  /*package*/ final ConceptDescriptor myConceptKeyword = createDescriptorForKeyword();
  /*package*/ final ConceptDescriptor myConceptPage = createDescriptorForPage();
  /*package*/ final ConceptDescriptor myConceptPageRegisterConfig = createDescriptorForPageRegisterConfig();
  /*package*/ final ConceptDescriptor myConceptPageShouldContainElement = createDescriptorForPageShouldContainElement();
  /*package*/ final ConceptDescriptor myConceptPageShouldContainText = createDescriptorForPageShouldContainText();
  /*package*/ final ConceptDescriptor myConceptPageShouldNotContainElement = createDescriptorForPageShouldNotContainElement();
  /*package*/ final ConceptDescriptor myConceptPageShouldNotContainText = createDescriptorForPageShouldNotContainText();
  /*package*/ final ConceptDescriptor myConceptPageToRegister = createDescriptorForPageToRegister();
  /*package*/ final ConceptDescriptor myConceptScroll = createDescriptorForScroll();
  /*package*/ final ConceptDescriptor myConceptScrollDown = createDescriptorForScrollDown();
  /*package*/ final ConceptDescriptor myConceptScrollUp = createDescriptorForScrollUp();
  /*package*/ final ConceptDescriptor myConceptSleep = createDescriptorForSleep();
  /*package*/ final ConceptDescriptor myConceptStep = createDescriptorForStep();
  /*package*/ final ConceptDescriptor myConceptSwipe = createDescriptorForSwipe();
  /*package*/ final ConceptDescriptor myConceptTap = createDescriptorForTap();
  /*package*/ final ConceptDescriptor myConceptTapByCoordinates = createDescriptorForTapByCoordinates();
  /*package*/ final ConceptDescriptor myConceptTextShouldBeVisible = createDescriptorForTextShouldBeVisible();
  /*package*/ final ConceptDescriptor myConceptWaitUntilElementIsVisible = createDescriptorForWaitUntilElementIsVisible();
  /*package*/ final ConceptDescriptor myConceptWaitUntilPageContains = createDescriptorForWaitUntilPageContains();
  /*package*/ final ConceptDescriptor myConceptWaitUntilPageContainsElement = createDescriptorForWaitUntilPageContainsElement();
  /*package*/ final ConceptDescriptor myConceptWaitUntilPageDoesNotContain = createDescriptorForWaitUntilPageDoesNotContain();
  /*package*/ final ConceptDescriptor myConceptWaitUntilPageDoesNotContainElement = createDescriptorForWaitUntilPageDoesNotContainElement();
  /*package*/ final EnumerationDescriptor myEnumerationStringBoolean = new EnumerationDescriptor_StringBoolean();
  /*package*/ final EnumerationDescriptor myEnumerationautomationNames = new EnumerationDescriptor_automationNames();
  /*package*/ final EnumerationDescriptor myEnumerationplataforms = new EnumerationDescriptor_plataforms();
  /*package*/ final EnumerationDescriptor myEnumerationselectors = new EnumerationDescriptor_selectors();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptCapturePageScreenshot, myConceptClearText, myConceptClickAPoint, myConceptClickElement, myConceptClickElementAtCoordinates, myConceptClickText, myConceptComponent, myConceptComponents, myConceptConfiguration, myConceptElementShouldBeDisabled, myConceptElementShouldBeEnabled, myConceptElementShouldBeVisible, myConceptElementShouldContainText, myConceptElementShouldNotContainText, myConceptElementTextShouldBe, myConceptExecuteAdbShell, myConceptExecuteScript, myConceptFlow, myConceptFlowItem, myConceptFlows, myConceptHideKeyboard, myConceptHooks, myConceptInputPassword, myConceptInputText, myConceptKeyword, myConceptPage, myConceptPageRegisterConfig, myConceptPageShouldContainElement, myConceptPageShouldContainText, myConceptPageShouldNotContainElement, myConceptPageShouldNotContainText, myConceptPageToRegister, myConceptScroll, myConceptScrollDown, myConceptScrollUp, myConceptSleep, myConceptStep, myConceptSwipe, myConceptTap, myConceptTapByCoordinates, myConceptTextShouldBeVisible, myConceptWaitUntilElementIsVisible, myConceptWaitUntilPageContains, myConceptWaitUntilPageContainsElement, myConceptWaitUntilPageDoesNotContain, myConceptWaitUntilPageDoesNotContainElement);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.CapturePageScreenshot:
        return myConceptCapturePageScreenshot;
      case LanguageConceptSwitch.ClearText:
        return myConceptClearText;
      case LanguageConceptSwitch.ClickAPoint:
        return myConceptClickAPoint;
      case LanguageConceptSwitch.ClickElement:
        return myConceptClickElement;
      case LanguageConceptSwitch.ClickElementAtCoordinates:
        return myConceptClickElementAtCoordinates;
      case LanguageConceptSwitch.ClickText:
        return myConceptClickText;
      case LanguageConceptSwitch.Component:
        return myConceptComponent;
      case LanguageConceptSwitch.Components:
        return myConceptComponents;
      case LanguageConceptSwitch.Configuration:
        return myConceptConfiguration;
      case LanguageConceptSwitch.ElementShouldBeDisabled:
        return myConceptElementShouldBeDisabled;
      case LanguageConceptSwitch.ElementShouldBeEnabled:
        return myConceptElementShouldBeEnabled;
      case LanguageConceptSwitch.ElementShouldBeVisible:
        return myConceptElementShouldBeVisible;
      case LanguageConceptSwitch.ElementShouldContainText:
        return myConceptElementShouldContainText;
      case LanguageConceptSwitch.ElementShouldNotContainText:
        return myConceptElementShouldNotContainText;
      case LanguageConceptSwitch.ElementTextShouldBe:
        return myConceptElementTextShouldBe;
      case LanguageConceptSwitch.ExecuteAdbShell:
        return myConceptExecuteAdbShell;
      case LanguageConceptSwitch.ExecuteScript:
        return myConceptExecuteScript;
      case LanguageConceptSwitch.Flow:
        return myConceptFlow;
      case LanguageConceptSwitch.FlowItem:
        return myConceptFlowItem;
      case LanguageConceptSwitch.Flows:
        return myConceptFlows;
      case LanguageConceptSwitch.HideKeyboard:
        return myConceptHideKeyboard;
      case LanguageConceptSwitch.Hooks:
        return myConceptHooks;
      case LanguageConceptSwitch.InputPassword:
        return myConceptInputPassword;
      case LanguageConceptSwitch.InputText:
        return myConceptInputText;
      case LanguageConceptSwitch.Keyword:
        return myConceptKeyword;
      case LanguageConceptSwitch.Page:
        return myConceptPage;
      case LanguageConceptSwitch.PageRegisterConfig:
        return myConceptPageRegisterConfig;
      case LanguageConceptSwitch.PageShouldContainElement:
        return myConceptPageShouldContainElement;
      case LanguageConceptSwitch.PageShouldContainText:
        return myConceptPageShouldContainText;
      case LanguageConceptSwitch.PageShouldNotContainElement:
        return myConceptPageShouldNotContainElement;
      case LanguageConceptSwitch.PageShouldNotContainText:
        return myConceptPageShouldNotContainText;
      case LanguageConceptSwitch.PageToRegister:
        return myConceptPageToRegister;
      case LanguageConceptSwitch.Scroll:
        return myConceptScroll;
      case LanguageConceptSwitch.ScrollDown:
        return myConceptScrollDown;
      case LanguageConceptSwitch.ScrollUp:
        return myConceptScrollUp;
      case LanguageConceptSwitch.Sleep:
        return myConceptSleep;
      case LanguageConceptSwitch.Step:
        return myConceptStep;
      case LanguageConceptSwitch.Swipe:
        return myConceptSwipe;
      case LanguageConceptSwitch.Tap:
        return myConceptTap;
      case LanguageConceptSwitch.TapByCoordinates:
        return myConceptTapByCoordinates;
      case LanguageConceptSwitch.TextShouldBeVisible:
        return myConceptTextShouldBeVisible;
      case LanguageConceptSwitch.WaitUntilElementIsVisible:
        return myConceptWaitUntilElementIsVisible;
      case LanguageConceptSwitch.WaitUntilPageContains:
        return myConceptWaitUntilPageContains;
      case LanguageConceptSwitch.WaitUntilPageContainsElement:
        return myConceptWaitUntilPageContainsElement;
      case LanguageConceptSwitch.WaitUntilPageDoesNotContain:
        return myConceptWaitUntilPageDoesNotContain;
      case LanguageConceptSwitch.WaitUntilPageDoesNotContainElement:
        return myConceptWaitUntilPageDoesNotContainElement;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList(myEnumerationStringBoolean, myEnumerationautomationNames, myEnumerationplataforms, myEnumerationselectors);
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForCapturePageScreenshot() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Teasy", "CapturePageScreenshot", 0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x67d09fa70ba57055L);
    b.class_(false, false, false);
    // extends: Teasy.structure.Step
    b.super_(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x29b0fffc80bf36a0L);
    b.origin("r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/7480654520866140245");
    b.version(3);
    b.alias("Capture Page Screenshot");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForClearText() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Teasy", "ClearText", 0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x1afad254c1f448f8L);
    b.class_(false, false, false);
    // extends: Teasy.structure.Step
    b.super_(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x29b0fffc80bf36a0L);
    b.origin("r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/1944097450636888312");
    b.version(3);
    b.associate("component", 0x1afad254c1f448f9L).target(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x637c9747e118846bL).optional(false).origin("1944097450636888313").done();
    b.alias("Clear Text");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForClickAPoint() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Teasy", "ClickAPoint", 0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x67d09fa70b2d0adaL);
    b.class_(false, false, false);
    // extends: Teasy.structure.Step
    b.super_(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x29b0fffc80bf36a0L);
    b.origin("r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/7480654520858249946");
    b.version(3);
    b.property("x", 0x67d09fa70b2d0adbL).type(PrimitiveTypeId.STRING).origin("7480654520858249947").done();
    b.property("y", 0x67d09fa70b2d0addL).type(PrimitiveTypeId.STRING).origin("7480654520858249949").done();
    b.property("duration", 0x67d09fa70b2d0ae0L).type(PrimitiveTypeId.INTEGER).origin("7480654520858249952").done();
    b.alias("Click A Point");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForClickElement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Teasy", "ClickElement", 0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x1afad254c1f432adL);
    b.class_(false, false, false);
    // extends: Teasy.structure.Step
    b.super_(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x29b0fffc80bf36a0L);
    b.origin("r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/1944097450636882605");
    b.version(3);
    b.associate("component", 0x1afad254c1f432b0L).target(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x637c9747e118846bL).optional(false).origin("1944097450636882608").done();
    b.alias("Click Element");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForClickElementAtCoordinates() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Teasy", "ClickElementAtCoordinates", 0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x67d09fa70b3db96cL);
    b.class_(false, false, false);
    // extends: Teasy.structure.Step
    b.super_(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x29b0fffc80bf36a0L);
    b.origin("r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/7480654520859343212");
    b.version(3);
    b.property("x", 0x67d09fa70b3db96eL).type(PrimitiveTypeId.STRING).origin("7480654520859343214").done();
    b.property("y", 0x67d09fa70b3db970L).type(PrimitiveTypeId.STRING).origin("7480654520859343216").done();
    b.alias("Click Element At Coordinates");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForClickText() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Teasy", "ClickText", 0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x67d09fa70b364c30L);
    b.class_(false, false, false);
    // extends: Teasy.structure.Step
    b.super_(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x29b0fffc80bf36a0L);
    b.origin("r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/7480654520858856496");
    b.version(3);
    b.property("text", 0x67d09fa70b364c31L).type(PrimitiveTypeId.STRING).origin("7480654520858856497").done();
    b.property("exact_match", 0x67d09fa70b364c32L).type(MetaIdFactory.dataTypeId(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x67d09fa70b364e0aL)).origin("7480654520858856498").done();
    b.alias("Click Text");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForComponent() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Teasy", "Component", 0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x637c9747e118846bL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/7168771041841939563");
    b.version(3);
    b.property("selector", 0x637c9747e118846eL).type(MetaIdFactory.dataTypeId(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x637c9747e1188470L)).origin("7168771041841939566").done();
    b.property("selector_value", 0x637c9747e1188484L).type(PrimitiveTypeId.STRING).origin("7168771041841939588").done();
    b.alias("Component");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForComponents() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Teasy", "Components", 0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x7dbf8857483dd032L);
    b.class_(false, false, true);
    b.origin("r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/9061110883748270130");
    b.version(3);
    b.aggregate("components", 0x7dbf8857483dd033L).target(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x637c9747e118846bL).optional(true).ordered(true).multiple(true).origin("9061110883748270131").done();
    b.alias("Components");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForConfiguration() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Teasy", "Configuration", 0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x637c9747e115f171L);
    b.class_(false, false, true);
    b.origin("r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/7168771041841770865");
    b.version(3);
    b.property("apk_name", 0x67d09fa70b20f9e0L).type(PrimitiveTypeId.STRING).origin("7480654520857459168").done();
    b.property("time_to_wait", 0x637c9747e115f182L).type(PrimitiveTypeId.INTEGER).origin("7168771041841770882").done();
    b.property("appium_server", 0x67d09fa70b0d6cd3L).type(PrimitiveTypeId.STRING).origin("7480654520856177875").done();
    b.property("platform_name", 0x67d09fa70b0d6cdbL).type(MetaIdFactory.dataTypeId(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x67d09fa70b0d6ce4L)).origin("7480654520856177883").done();
    b.property("device_name", 0x67d09fa70b0d6ce6L).type(PrimitiveTypeId.STRING).origin("7480654520856177894").done();
    b.property("app_package", 0x67d09fa70b0d6cf0L).type(PrimitiveTypeId.STRING).origin("7480654520856177904").done();
    b.property("app_activity", 0x67d09fa70b0d6cfbL).type(PrimitiveTypeId.STRING).origin("7480654520856177915").done();
    b.property("automation_name", 0x67d09fa70b0d6d07L).type(MetaIdFactory.dataTypeId(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x67d09fa70b0d6d5bL)).origin("7480654520856177927").done();
    b.alias("Configuration");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForElementShouldBeDisabled() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Teasy", "ElementShouldBeDisabled", 0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x67d09fa70ba879f4L);
    b.class_(false, false, false);
    // extends: Teasy.structure.Step
    b.super_(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x29b0fffc80bf36a0L);
    b.origin("r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/7480654520866339316");
    b.version(3);
    b.associate("component", 0x67d09fa70ba879f5L).target(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x637c9747e118846bL).optional(false).origin("7480654520866339317").done();
    b.alias("Element Should Be Disabled");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForElementShouldBeEnabled() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Teasy", "ElementShouldBeEnabled", 0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x67d09fa70bab962aL);
    b.class_(false, false, false);
    // extends: Teasy.structure.Step
    b.super_(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x29b0fffc80bf36a0L);
    b.origin("r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/7480654520866543146");
    b.version(3);
    b.associate("component", 0x67d09fa70bab962bL).target(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x637c9747e118846bL).optional(false).origin("7480654520866543147").done();
    b.alias("Element Should Be Enabled");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForElementShouldBeVisible() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Teasy", "ElementShouldBeVisible", 0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x67d09fa70baec48dL);
    b.class_(false, false, false);
    // extends: Teasy.structure.Step
    b.super_(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x29b0fffc80bf36a0L);
    b.origin("r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/7480654520866751629");
    b.version(3);
    b.associate("component", 0x67d09fa70baec48eL).target(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x637c9747e118846bL).optional(false).origin("7480654520866751630").done();
    b.alias("Element Should Be Visible");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForElementShouldContainText() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Teasy", "ElementShouldContainText", 0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x67d09fa70bb20582L);
    b.class_(false, false, false);
    // extends: Teasy.structure.Step
    b.super_(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x29b0fffc80bf36a0L);
    b.origin("r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/7480654520866964866");
    b.version(3);
    b.property("text", 0x67d09fa70bb2064cL).type(PrimitiveTypeId.STRING).origin("7480654520866965068").done();
    b.associate("component", 0x67d09fa70bb20583L).target(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x637c9747e118846bL).optional(false).origin("7480654520866964867").done();
    b.alias("Element Should Contain Text");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForElementShouldNotContainText() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Teasy", "ElementShouldNotContainText", 0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x67d09fa70bbb5c4eL);
    b.class_(false, false, false);
    // extends: Teasy.structure.Step
    b.super_(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x29b0fffc80bf36a0L);
    b.origin("r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/7480654520867576910");
    b.version(3);
    b.property("text", 0x67d09fa70bbb5c4fL).type(PrimitiveTypeId.STRING).origin("7480654520867576911").done();
    b.associate("component", 0x67d09fa70bbb5c50L).target(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x637c9747e118846bL).optional(false).origin("7480654520867576912").done();
    b.alias("Element Should Not Contain Text");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForElementTextShouldBe() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Teasy", "ElementTextShouldBe", 0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x67d09fa70bbed5ceL);
    b.class_(false, false, false);
    // extends: Teasy.structure.Step
    b.super_(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x29b0fffc80bf36a0L);
    b.origin("r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/7480654520867804622");
    b.version(3);
    b.property("text", 0x67d09fa70bbed5cfL).type(PrimitiveTypeId.STRING).origin("7480654520867804623").done();
    b.associate("component", 0x67d09fa70bbed5d0L).target(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x637c9747e118846bL).optional(false).origin("7480654520867804624").done();
    b.alias("Element Text Should Be");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForExecuteAdbShell() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Teasy", "ExecuteAdbShell", 0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x1afad254c1f432fbL);
    b.class_(false, false, false);
    // extends: Teasy.structure.Step
    b.super_(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x29b0fffc80bf36a0L);
    b.origin("r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/1944097450636882683");
    b.version(3);
    b.property("function", 0x1afad254c1f432fcL).type(PrimitiveTypeId.STRING).origin("1944097450636882684").done();
    b.property("arguments", 0x67d09fa70b427073L).type(PrimitiveTypeId.STRING).origin("7480654520859652211").done();
    b.alias("Execute Adb Shell");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForExecuteScript() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Teasy", "ExecuteScript", 0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x67d09fa70b473f93L);
    b.class_(false, false, false);
    // extends: Teasy.structure.Step
    b.super_(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x29b0fffc80bf36a0L);
    b.origin("r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/7480654520859967379");
    b.version(3);
    b.property("function", 0x67d09fa70b473f94L).type(PrimitiveTypeId.STRING).origin("7480654520859967380").done();
    b.alias("Execute Script");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForFlow() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Teasy", "Flow", 0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x4326e26a2123e15dL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/4838803795106586973");
    b.version(3);
    b.aggregate("flow_item", 0x4326e26a2123e162L).target(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x4326e26a2123e121L).optional(false).ordered(true).multiple(true).origin("4838803795106586978").done();
    b.alias("Flow");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForFlowItem() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Teasy", "FlowItem", 0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x4326e26a2123e121L);
    b.class_(false, false, false);
    b.origin("r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/4838803795106586913");
    b.version(3);
    b.associate("action", 0x4326e26a2123e128L).target(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x29b0fffc80bf369dL).optional(false).origin("4838803795106586920").done();
    b.alias("Action To Execute");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForFlows() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Teasy", "Flows", 0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x4326e26a2135e169L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/4838803795107766633");
    b.version(3);
    b.aggregate("flow", 0x4326e26a2135e16aL).target(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x4326e26a2123e15dL).optional(false).ordered(true).multiple(true).origin("4838803795107766634").done();
    b.alias("Flows");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForHideKeyboard() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Teasy", "HideKeyboard", 0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x39abebde7ab0d751L);
    b.class_(false, false, false);
    // extends: Teasy.structure.Step
    b.super_(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x29b0fffc80bf36a0L);
    b.origin("r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/4155674421953091409");
    b.version(3);
    b.alias("Hide Keyboard");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForHooks() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Teasy", "Hooks", 0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x3d4bb2987a5388f8L);
    b.class_(false, false, true);
    b.origin("r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/4416820227523971320");
    b.version(3);
    b.alias("Hooks");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForInputPassword() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Teasy", "InputPassword", 0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x67d09fa70b5fffa4L);
    b.class_(false, false, false);
    // extends: Teasy.structure.Step
    b.super_(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x29b0fffc80bf36a0L);
    b.origin("r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/7480654520861589412");
    b.version(3);
    b.property("password", 0x67d09fa70b5fffa5L).type(PrimitiveTypeId.STRING).origin("7480654520861589413").done();
    b.associate("component", 0x67d09fa70b5fffa6L).target(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x637c9747e118846bL).optional(false).origin("7480654520861589414").done();
    b.alias("Input Password");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForInputText() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Teasy", "InputText", 0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x29b0fffc80c7b56fL);
    b.class_(false, false, false);
    // extends: Teasy.structure.Step
    b.super_(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x29b0fffc80bf36a0L);
    b.origin("r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/3004182411413534063");
    b.version(3);
    b.property("text", 0x29b0fffc80c7b572L).type(PrimitiveTypeId.STRING).origin("3004182411413534066").done();
    b.associate("component", 0x29b0fffc80c7b570L).target(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x637c9747e118846bL).optional(false).origin("3004182411413534064").done();
    b.alias("Input Text");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForKeyword() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Teasy", "Keyword", 0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x29b0fffc80bf369dL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/3004182411412977309");
    b.version(3);
    b.aggregate("step", 0x29b0fffc80bf36a8L).target(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x29b0fffc80bf36a0L).optional(false).ordered(true).multiple(true).origin("3004182411412977320").done();
    b.alias("Keyword");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPage() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Teasy", "Page", 0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x29b0fffc80bf36a1L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/3004182411412977313");
    b.version(3);
    b.aggregate("keyword", 0x29b0fffc80bf36a4L).target(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x29b0fffc80bf369dL).optional(false).ordered(true).multiple(true).origin("3004182411412977316").done();
    b.alias("Page");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPageRegisterConfig() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Teasy", "PageRegisterConfig", 0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x4b2c28ff7a1373d5L);
    b.class_(false, false, true);
    b.origin("r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/5416749529549730773");
    b.version(3);
    b.aggregate("pages", 0x4b2c28ff7a1373d6L).target(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x4b2c28ff7a1373d8L).optional(false).ordered(true).multiple(true).origin("5416749529549730774").done();
    b.alias("PageRegisterConfig");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPageShouldContainElement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Teasy", "PageShouldContainElement", 0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x1afad254c1f4345eL);
    b.class_(false, false, false);
    // extends: Teasy.structure.Step
    b.super_(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x29b0fffc80bf36a0L);
    b.origin("r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/1944097450636883038");
    b.version(3);
    b.associate("component", 0x1afad254c1f4345fL).target(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x637c9747e118846bL).optional(false).origin("1944097450636883039").done();
    b.alias("Page Should Contain Element");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPageShouldContainText() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Teasy", "PageShouldContainText", 0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x1afad254c1f4341dL);
    b.class_(false, false, false);
    // extends: Teasy.structure.Step
    b.super_(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x29b0fffc80bf36a0L);
    b.origin("r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/1944097450636882973");
    b.version(3);
    b.property("text", 0x1afad254c1f4341eL).type(PrimitiveTypeId.STRING).origin("1944097450636882974").done();
    b.alias("Page Should Contain Text");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPageShouldNotContainElement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Teasy", "PageShouldNotContainElement", 0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x1afad254c1f434acL);
    b.class_(false, false, false);
    // extends: Teasy.structure.Step
    b.super_(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x29b0fffc80bf36a0L);
    b.origin("r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/1944097450636883116");
    b.version(3);
    b.associate("component", 0x1afad254c1f434adL).target(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x637c9747e118846bL).optional(false).origin("1944097450636883117").done();
    b.alias("Page Should Not Contain Element");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPageShouldNotContainText() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Teasy", "PageShouldNotContainText", 0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x1afad254c1f434aaL);
    b.class_(false, false, false);
    // extends: Teasy.structure.Step
    b.super_(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x29b0fffc80bf36a0L);
    b.origin("r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/1944097450636883114");
    b.version(3);
    b.property("text", 0x1afad254c1f434abL).type(PrimitiveTypeId.STRING).origin("1944097450636883115").done();
    b.alias("Page Should Not Contain Text");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPageToRegister() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Teasy", "PageToRegister", 0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x4b2c28ff7a1373d8L);
    b.class_(false, false, false);
    b.origin("r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/5416749529549730776");
    b.version(3);
    b.associate("page_name", 0x4b2c28ff7a1373daL).target(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x29b0fffc80bf36a1L).optional(false).origin("5416749529549730778").done();
    b.alias("PageRegister");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForScroll() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Teasy", "Scroll", 0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x67d09fa70b93b2bbL);
    b.class_(false, false, false);
    // extends: Teasy.structure.Step
    b.super_(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x29b0fffc80bf36a0L);
    b.origin("r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/7480654520864977595");
    b.version(3);
    b.associate("start", 0x67d09fa70b93b2bcL).target(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x637c9747e118846bL).optional(false).origin("7480654520864977596").done();
    b.associate("end", 0x67d09fa70b93b2beL).target(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x637c9747e118846bL).optional(false).origin("7480654520864977598").done();
    b.alias("Scroll");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForScrollDown() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Teasy", "ScrollDown", 0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x67d09fa70b9c70cdL);
    b.class_(false, false, false);
    // extends: Teasy.structure.Step
    b.super_(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x29b0fffc80bf36a0L);
    b.origin("r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/7480654520865550541");
    b.version(3);
    b.associate("component", 0x67d09fa70b9c70ceL).target(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x637c9747e118846bL).optional(false).origin("7480654520865550542").done();
    b.alias("Scroll Down");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForScrollUp() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Teasy", "ScrollUp", 0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x67d09fa70ba266e5L);
    b.class_(false, false, false);
    // extends: Teasy.structure.Step
    b.super_(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x29b0fffc80bf36a0L);
    b.origin("r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/7480654520865941221");
    b.version(3);
    b.associate("component", 0x67d09fa70ba266e6L).target(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x637c9747e118846bL).optional(false).origin("7480654520865941222").done();
    b.alias("Scroll Up");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSleep() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Teasy", "Sleep", 0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x1afad254c1f4486aL);
    b.class_(false, false, false);
    // extends: Teasy.structure.Step
    b.super_(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x29b0fffc80bf36a0L);
    b.origin("r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/1944097450636888170");
    b.version(3);
    b.property("time", 0x1afad254c1f44950L).type(PrimitiveTypeId.INTEGER).origin("1944097450636888400").done();
    b.alias("Sleep");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForStep() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Teasy", "Step", 0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x29b0fffc80bf36a0L);
    b.class_(false, true, false);
    b.origin("r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/3004182411412977312");
    b.version(3);
    b.alias("Step");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSwipe() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Teasy", "Swipe", 0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x67d09fa70b8898daL);
    b.class_(false, false, false);
    // extends: Teasy.structure.Step
    b.super_(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x29b0fffc80bf36a0L);
    b.origin("r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/7480654520864250074");
    b.version(3);
    b.property("start_x", 0x67d09fa70b8898ddL).type(PrimitiveTypeId.STRING).origin("7480654520864250077").done();
    b.property("start_y", 0x67d09fa70b8898dfL).type(PrimitiveTypeId.STRING).origin("7480654520864250079").done();
    b.property("offset_x", 0x67d09fa70b8898e2L).type(PrimitiveTypeId.STRING).origin("7480654520864250082").done();
    b.property("offset_y", 0x67d09fa70b8898e6L).type(PrimitiveTypeId.STRING).origin("7480654520864250086").done();
    b.property("duration", 0x67d09fa70b8898ebL).type(PrimitiveTypeId.INTEGER).origin("7480654520864250091").done();
    b.alias("Swipe");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTap() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Teasy", "Tap", 0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x1afad254c1f4336bL);
    b.class_(false, false, false);
    // extends: Teasy.structure.Step
    b.super_(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x29b0fffc80bf36a0L);
    b.origin("r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/1944097450636882795");
    b.version(3);
    b.property("count", 0x1afad254c1f4336eL).type(PrimitiveTypeId.INTEGER).origin("1944097450636882798").done();
    b.associate("component", 0x67d09fa70b770cfeL).target(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x637c9747e118846bL).optional(false).origin("7480654520863100158").done();
    b.alias("Tap");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTapByCoordinates() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Teasy", "TapByCoordinates", 0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x67d09fa70b80a02bL);
    b.class_(false, false, false);
    // extends: Teasy.structure.Step
    b.super_(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x29b0fffc80bf36a0L);
    b.origin("r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/7480654520863727659");
    b.version(3);
    b.property("count", 0x67d09fa70b80a02dL).type(PrimitiveTypeId.INTEGER).origin("7480654520863727661").done();
    b.property("x", 0x67d09fa70b80a02eL).type(PrimitiveTypeId.STRING).origin("7480654520863727662").done();
    b.property("y", 0x67d09fa70b80a031L).type(PrimitiveTypeId.STRING).origin("7480654520863727665").done();
    b.alias("Tap By Coordinates");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTextShouldBeVisible() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Teasy", "TextShouldBeVisible", 0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x67d09fa70b4e88baL);
    b.class_(false, false, false);
    // extends: Teasy.structure.Step
    b.super_(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x29b0fffc80bf36a0L);
    b.origin("r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/7480654520860444858");
    b.version(3);
    b.property("text", 0x67d09fa70b4e88bbL).type(PrimitiveTypeId.STRING).origin("7480654520860444859").done();
    b.property("exact_match", 0x67d09fa70b4e88bcL).type(MetaIdFactory.dataTypeId(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x67d09fa70b364e0aL)).origin("7480654520860444860").done();
    b.alias("Text Should Be Visible");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForWaitUntilElementIsVisible() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Teasy", "WaitUntilElementIsVisible", 0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x1afad254c1f44869L);
    b.class_(false, false, false);
    // extends: Teasy.structure.Step
    b.super_(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x29b0fffc80bf36a0L);
    b.origin("r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/1944097450636888169");
    b.version(3);
    b.property("timeout", 0x1afad254c1f44952L).type(PrimitiveTypeId.INTEGER).origin("1944097450636888402").done();
    b.associate("component", 0x1afad254c1f4486bL).target(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x637c9747e118846bL).optional(false).origin("1944097450636888171").done();
    b.alias("Wait Until Element Is Visible");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForWaitUntilPageContains() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Teasy", "WaitUntilPageContains", 0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x4f2a0581122bf7e4L);
    b.class_(false, false, false);
    // extends: Teasy.structure.Step
    b.super_(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x29b0fffc80bf36a0L);
    b.origin("r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/5704377929931945956");
    b.version(3);
    b.property("text", 0x4f2a0581122bf7f7L).type(PrimitiveTypeId.STRING).origin("5704377929931945975").done();
    b.property("timeout", 0x4f2a0581122bf7f9L).type(PrimitiveTypeId.INTEGER).origin("5704377929931945977").done();
    b.alias("Wait Until Page Contains");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForWaitUntilPageContainsElement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Teasy", "WaitUntilPageContainsElement", 0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x4f2a0581122bf8e8L);
    b.class_(false, false, false);
    // extends: Teasy.structure.Step
    b.super_(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x29b0fffc80bf36a0L);
    b.origin("r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/5704377929931946216");
    b.version(3);
    b.property("timeout", 0x4f2a0581122bf8eaL).type(PrimitiveTypeId.INTEGER).origin("5704377929931946218").done();
    b.associate("component", 0x4f2a0581122bf8ecL).target(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x637c9747e118846bL).optional(false).origin("5704377929931946220").done();
    b.alias("Wait Until Page Contains Element");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForWaitUntilPageDoesNotContain() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Teasy", "WaitUntilPageDoesNotContain", 0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x4f2a0581122bf96dL);
    b.class_(false, false, false);
    // extends: Teasy.structure.Step
    b.super_(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x29b0fffc80bf36a0L);
    b.origin("r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/5704377929931946349");
    b.version(3);
    b.property("timeout", 0x4f2a0581122bf96fL).type(PrimitiveTypeId.INTEGER).origin("5704377929931946351").done();
    b.property("text", 0x4f2a0581122bf99cL).type(PrimitiveTypeId.STRING).origin("5704377929931946396").done();
    b.alias("Wait Until Page Does Not Contain");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForWaitUntilPageDoesNotContainElement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Teasy", "WaitUntilPageDoesNotContainElement", 0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x4f2a0581122bf99fL);
    b.class_(false, false, false);
    // extends: Teasy.structure.Step
    b.super_(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x29b0fffc80bf36a0L);
    b.origin("r:fa4deac7-a8d4-4bef-9b2d-db266658ed18(Teasy.structure)/5704377929931946399");
    b.version(3);
    b.property("timeout", 0x4f2a0581122bf9a1L).type(PrimitiveTypeId.INTEGER).origin("5704377929931946401").done();
    b.associate("component", 0x4f2a0581122bf9a0L).target(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x637c9747e118846bL).optional(false).origin("5704377929931946400").done();
    b.alias("Wait Until Page Does Not Contain Element");
    return b.create();
  }
}
