package Teasy.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class ClickElementAtCoordinates_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("    Click Element At Coordinates    ");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.x$sHRI));
    tgs.append("    ");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.y$sIlK));
    tgs.newLine();
  }

  private static final class PROPS {
    /*package*/ static final SProperty x$sHRI = MetaAdapterFactory.getProperty(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x67d09fa70b3db96cL, 0x67d09fa70b3db96eL, "x");
    /*package*/ static final SProperty y$sIlK = MetaAdapterFactory.getProperty(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x67d09fa70b3db96cL, 0x67d09fa70b3db970L, "y");
  }
}
