package Teasy.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;

public class Hooks_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("*** Settings ***");
    tgs.newLine();
    tgs.indent();
    tgs.append("\nDocumentation       Global Hooks (Run appium with this arg \"--relaxed-security\")");
    tgs.newLine();
    tgs.indent();
    tgs.append("...");
    tgs.newLine();
    tgs.indent();
    tgs.append("...                   In order to carry out the hooks of our tests,");
    tgs.newLine();
    tgs.newLine();
    tgs.indent();
    tgs.append("...                   we can use hooks to open the application");
    tgs.newLine();
    tgs.indent();
    tgs.append("...                   and close the application at the end of the tests.");
    tgs.newLine();
    tgs.indent();
    tgs.append("...");
    tgs.newLine();
    tgs.indent();
    tgs.append("...                   For that we import the commons steps here to use");
    tgs.newLine();
    tgs.indent();
    tgs.append("...                   the global variables that it has. Centralizing the information.");
    tgs.newLine();
    tgs.newLine();
    tgs.indent();
    tgs.append("Library               AppiumLibrary");
    tgs.newLine();
    tgs.append("Resource              ../../config/config.robot");
    tgs.newLine();
    tgs.newLine();
    tgs.append("*** Keywords ***");
    tgs.newLine();
    tgs.indent();
    tgs.append("ANDROID TEST SETUP");
    tgs.newLine();
    tgs.append("    Open Application    ${APPIUM_SERVER}");
    tgs.newLine();
    tgs.append("    ...                 platformName=${PLATFORM_NAME}");
    tgs.newLine();
    tgs.append("    ...                 deviceName=${DEVICE_NAME}");
    tgs.newLine();
    tgs.append("    ...                 appPackage=${APP_PACKAGE}");
    tgs.newLine();
    tgs.append("    ...                 appActivity=${APP_ACTIVITY}");
    tgs.newLine();
    tgs.append("    ...                 automationName=${AUTOMATION_NAME}");
    tgs.newLine();
    tgs.append("    ...                 app=${APP_PATH}");
    tgs.newLine();
    tgs.newLine();
    tgs.append("ANDROID TEST SETUP");
    tgs.newLine();
    tgs.append("    Set Appium Timeout  ${TIME_TO_WAIT}");
    tgs.newLine();
    tgs.append("    Launch Application");
    tgs.newLine();
    tgs.newLine();
    tgs.append("END TEST");
    tgs.newLine();
    tgs.append("    Capture Page Screenshot");
    tgs.newLine();
    tgs.append("    Quit Application");
    tgs.newLine();
  }
}
