package Teasy.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class TapByCoordinates_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("    Tap    ${None}    x_offset=");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.x$jGR4));
    tgs.append("    y_offset=");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.y$jH$7));
    tgs.append("    count=");
    tgs.append(Integer.toString(SPropertyOperations.getInteger(ctx.getPrimaryInput(), PROPS.count$jGC3)));
    tgs.newLine();
  }

  private static final class PROPS {
    /*package*/ static final SProperty x$jGR4 = MetaAdapterFactory.getProperty(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x67d09fa70b80a02bL, 0x67d09fa70b80a02eL, "x");
    /*package*/ static final SProperty y$jH$7 = MetaAdapterFactory.getProperty(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x67d09fa70b80a02bL, 0x67d09fa70b80a031L, "y");
    /*package*/ static final SProperty count$jGC3 = MetaAdapterFactory.getProperty(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x67d09fa70b80a02bL, 0x67d09fa70b80a02dL, "count");
  }
}
