package Teasy.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SEnumOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class TextShouldBeVisible_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("    Text Should Be Visible    ");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.text$$tqH));
    tgs.append("    exact_match=");
    tgs.append(SEnumOperations.getMemberPresentation(SPropertyOperations.getEnum(ctx.getPrimaryInput(), PROPS.exact_match$$y_3)));
    tgs.newLine();
  }

  private static final class PROPS {
    /*package*/ static final SProperty text$$tqH = MetaAdapterFactory.getProperty(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x67d09fa70b4e88baL, 0x67d09fa70b4e88bbL, "text");
    /*package*/ static final SProperty exact_match$$y_3 = MetaAdapterFactory.getProperty(0x67c1fa65c7ac493dL, 0xb11b664188147c91L, 0x67d09fa70b4e88baL, 0x67d09fa70b4e88bcL, "exact_match");
  }
}
